In [1]:
!nvidia-smi

Wed Jun 12 18:55:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 537.13                 Driver Version: 537.13       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   53C    P8               5W /  60W |   1406MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [2]:
!pip show torch                     

Name: torch
Version: 2.1.0+cu118
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: C:\Users\sasha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages
Requires: filelock, fsspec, jinja2, networkx, sympy, typing-extensions
Required-by: asteroid-filterbanks, julius, lightning, pyannote.audio, pytorch-lightning, pytorch-metric-learning, speechbrain, torch-audiomentations, torch-pitch-shift, torchaudio, torchmetrics, torchvision, voicefixer


In [ ]:
!pip uninstall torch

In [ ]:
!pip uninstall torchaudio

In [ ]:
!pip uninstall torchvision

In [10]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

Looking in indexes: https://download.pytorch.org/whl/cu121
     ---------------------------------------- 0.0/2.5 GB ? eta -:--:--
     ---------------------------------------- 0.0/2.5 GB ? eta -:--:--
     ---------------------------------------- 0.0/2.5 GB 217.9 kB/s eta 3:09:15
     ---------------------------------------- 0.0/2.5 GB 435.7 kB/s eta 1:34:38
     ---------------------------------------- 0.0/2.5 GB 381.3 kB/s eta 1:48:09
     ---------------------------------------- 0.0/2.5 GB 607.9 kB/s eta 1:07:50
     ---------------------------------------- 0.0/2.5 GB 726.2 kB/s eta 0:56:47
     ---------------------------------------- 0.0/2.5 GB 948.8 kB/s eta 0:43:28
     ---------------------------------------- 0.0/2.5 GB 1.1 MB/s eta 0:37:45
     ---------------------------------------- 0.0/2.5 GB 1.5 MB/s eta 0:27:24
     ---------------------------------------- 0.0/2.5 GB 1.8 MB/s eta 0:22:29
     ---------------------------------------- 0.0/2.5 GB 1.9 MB/s eta 0:21:14
     --

ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device



In [5]:
!pip install cuda-python

   ---------------------------------------- 0.0/10.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.2 MB 435.7 kB/s eta 0:00:24
   ---------------------------------------- 0.0/10.2 MB 393.8 kB/s eta 0:00:26
   ---------------------------------------- 0.0/10.2 MB 393.8 kB/s eta 0:00:26
   ---------------------------------------- 0.1/10.2 MB 416.7 kB/s eta 0:00:25
   ---------------------------------------- 0.1/10.2 MB 350.1 kB/s eta 0:00:29
   ---------------------------------------- 0.1/10.2 MB 350.1 kB/s eta 0:00:29
   ---------------------------------------- 0.1/10.2 MB 344.8 kB/s eta 0:00:30
   ---------------------------------------- 0.1/10.2 MB 327.4 kB/s eta 0:00:31
    --------------------------------------- 0.1/10.2 MB 315.4 kB/s eta 0:00:32
    --------------------------------------- 0.1/10.2 MB 315.4 kB/s eta 0:00:32


DEPRECATION: voicefixer 0.1.2 has a non-standard dependency specifier streamlit>=1.12.0pyyaml. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of voicefixer or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [2]:
import torch
import torchvision
torch.cuda.is_available()

True

In [3]:
torch.__version__

'2.1.0+cu118'

In [7]:
# for speechbrain
!pip install speechbrain

# pyannote.audio
!pip install pyannote.audio

#!pip install -qq pytorch

!pip install pydub

In [1]:
!pip install --upgrade pyannote.audio

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com


DEPRECATION: voicefixer 0.1.2 has a non-standard dependency specifier streamlit>=1.12.0pyyaml. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of voicefixer or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [ ]:
Функция, которая проводит разделение аудиофайла на аудиофайлы соответствующие своим акторам.

filename - название аудиофайла с расширением wav. 
    Аудиофайл должен быть загружен в папку Files.

ВНИМАНИЕ: В НАЗВАНИИ ФАЙЛА НЕ ДОЛЖНО БЫТЬ ПРОБЕЛОВ

In [1]:
import glob, sys, os
import torchaudio
import datetime
import time
import torch
from IPython.display import Audio
from IPython import display

from speechbrain.inference.speaker import EncoderClassifier
from speechbrain.inference.speaker import SpeakerRecognition
from speechbrain.dataio.dataio import read_audio

classifier = EncoderClassifier.from_hparams(
    source="speechbrain/spkrec-ecapa-voxceleb",
    run_opts={"device":"cuda"}
)

verification = SpeakerRecognition.from_hparams(
    source="speechbrain/spkrec-ecapa-voxceleb", 
    savedir="pretrained_models/spkrec-ecapa-voxceleb",
    run_opts={"device":"cuda"}
)


from pyannote.audio import Pipeline

pipeline = Pipeline.from_pretrained(
    "pyannote/speaker-diarization-3.1", 
    use_auth_token="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"
)
pipeline.to(torch.device("cuda"))



samplesDir = "interviewer_samples/"

samples = ["interviewer_female1.wav",
           "interviewer_female10.wav",
           "interviewer_female11.wav",
           "interviewer_male12.wav"
          ]

mainPath = "C:/Users/sasha/OneDrive/Desktop/НИР/New Research/"
audioDirStr = "audio/"
diarDirStr = "diarization/"
ref = "Reference/"

C:\Users\sasha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pyannote\audio\core\io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
C:\Users\sasha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch_audiomentations\utils\io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")


In [16]:
pipeline.device

device(type='cuda')

In [3]:
filePath = mainPath + audioDirStr + "default"
directory_files = os.listdir(filePath)
for file in directory_files:
    print(os.path.splitext(os.path.basename(file))[0])

1
10
11
12
13
14
15
2
3
4
5
6
7
8
9


In [4]:
def diarFun(folderName):
    fileFolderPath = mainPath + audioDirStr + folderName
    rttmFolderPath = mainPath + diarDirStr + folderName
    if not os.path.exists(rttmFolderPath):
        os.mkdir(rttmFolderPath)
    directory_files = os.listdir(fileFolderPath)

    for file in directory_files:
        diarization = pipeline(fileFolderPath + '/' + file)
        rttmPath = rttmFolderPath + '/' + os.path.splitext(os.path.basename(file))[0] + '.rttm'
        with open(rttmPath, "w") as rttm:
            diarization.write_rttm(rttm)
        print("Текстовая диаризация " + file + " успешна")

In [5]:
allMethods = ["default","normalized","MTL","MTL_Normalized","MetricGAN","MetricGAN_Normalized",
              "deepFilterNet1","deepFilterNet1_normalized","deepFilterNet2","deepFilterNet2_normalized",
             "deepFilterNet3","deepFilterNet3_normalized"]

choosedMethods = ["deepFilterNet1_normalized", "deepFilterNet2","deepFilterNet2_normalized", "deepFilterNet3","deepFilterNet3_normalized"]

for method in allMethods:
    diarFun(method)

Текстовая диаризация 1.wav успешна
Текстовая диаризация 10.wav успешна
Текстовая диаризация 11.wav успешна
Текстовая диаризация 12.wav успешна
Текстовая диаризация 13.wav успешна
Текстовая диаризация 14.wav успешна
Текстовая диаризация 15.wav успешна
Текстовая диаризация 2.wav успешна
Текстовая диаризация 3.wav успешна
Текстовая диаризация 4.wav успешна
Текстовая диаризация 5.wav успешна
Текстовая диаризация 6.wav успешна
Текстовая диаризация 7.wav успешна
Текстовая диаризация 8.wav успешна
Текстовая диаризация 9.wav успешна
Текстовая диаризация 1.wav успешна
Текстовая диаризация 10.wav успешна
Текстовая диаризация 11.wav успешна
Текстовая диаризация 12.wav успешна
Текстовая диаризация 13.wav успешна
Текстовая диаризация 14.wav успешна
Текстовая диаризация 15.wav успешна
Текстовая диаризация 2.wav успешна
Текстовая диаризация 3.wav успешна
Текстовая диаризация 4.wav успешна
Текстовая диаризация 5.wav успешна
Текстовая диаризация 6.wav успешна
Текстовая диаризация 7.wav успешна
Текстова

In [24]:
import numpy as np

def convert_pydub_to_torchaudio(audio_segment):
    # Get the raw data
    cropped_audio.export(f"{output_path}/cropped_{i}.wav", format="wav")

    # Reshape raw data and adjust volume
    reshaped_data = raw_data.reshape((audio_segment.channels, -1))
    reshaped_data = reshaped_data / (1<<15)

    # Convert to tensor
    tensor_audio = torch.from_numpy(reshaped_data)

    # Get the sample rate
    sample_rate = audio_segment.frame_rate

    return tensor_audio, sample_rate

In [22]:
from pydub import AudioSegment

def speaker_detection(audio_path, rttm_path, sample, output_path):
    audio = AudioSegment.from_file(audio_path)
    
    with open(rttm_path, 'r') as file:
        lines = file.readlines()

    signal1, fs1 = torchaudio.load("interviewer_samples/" + sample + ".wav")
    
    max_speaker = ""
    max_score = 0;
    for speaker in get_all_speakers(rttm_path):
        score_count = 0
        time = 0
        prediction_sum = 0
        prediction_count = 0
        for i, line in enumerate(lines):
            parts = line.strip().split()
            if parts[7] == speaker:
                start_time = float(parts[3]) * 1000  # convert to milliseconds
                duration = float(parts[4]) * 1000  # convert to milliseconds
                end_time = start_time + duration
                
                if duration > 1000:
                    cropped_audio = audio[start_time:end_time]
                    path = f"{output_path}/cropped_{i}.wav"
                    cropped_audio.export(path, format="wav")
                    signal2, fs2 = torchaudio.load(path)
                    #print(end_time)
                    #embeddings = classifier.encode_batch(signal2)
                    score, prediction = verification.verify_batch(signal1, signal2)
                    if prediction:
                        prediction_sum += 1
                    prediction_count += 1
                    score_count += score
                    #print(score_count)
                    time += duration
        #print(prediction_count)
        #print(prediction_sum)
        if (time != 0):
            avg_score = score_count/(time/1000)
            #print(time)
            #print(avg_score)
            if avg_score > max_score:
                max_score = avg_score
                max_speaker = speaker

    print(max_score)
    print(max_speaker)

    with open("new_diar/" + rttm_path.split("/")[-2] + "/" + rttm_path.split("/")[-1], "w") as new_file:
        for speaker in get_all_speakers(rttm_path):
            for i, line in enumerate(lines):
                parts = line.strip().split()
                if parts[7] == max_speaker:
                    parts[7] = "Interviewer"
                    updated_line = " ".join(parts)  # Объединяем обновленные части строки
                    new_file.write(updated_line + "\n")  # Записываем в новый файл с переносом строки
                else:
                    new_file.write(line)  # Записываем остальные строки без изменений
                

In [23]:
for method in allMethods:
    for i in range(1, 16):
        speaker_detection("audio/default/" + str(i) + ".wav", "diarization/" + method + "/" + str(i) + ".rttm", str(i), "crop")

tensor([[0.1986]], device='cuda:0')
SPEAKER_00
tensor([[0.1382]], device='cuda:0')
SPEAKER_00
tensor([[0.2053]], device='cuda:0')
SPEAKER_01
tensor([[0.1961]], device='cuda:0')
SPEAKER_01
tensor([[0.1575]], device='cuda:0')
SPEAKER_01
tensor([[0.1696]], device='cuda:0')
SPEAKER_00
tensor([[0.1631]], device='cuda:0')
SPEAKER_00
tensor([[0.2230]], device='cuda:0')
SPEAKER_01
tensor([[0.1482]], device='cuda:0')
SPEAKER_00
tensor([[0.2290]], device='cuda:0')
SPEAKER_01
tensor([[0.2846]], device='cuda:0')
SPEAKER_01
tensor([[0.2195]], device='cuda:0')
SPEAKER_02
tensor([[0.1827]], device='cuda:0')
SPEAKER_00
tensor([[0.1877]], device='cuda:0')
SPEAKER_00
tensor([[0.2145]], device='cuda:0')
SPEAKER_00
tensor([[0.2012]], device='cuda:0')
SPEAKER_00
tensor([[0.1424]], device='cuda:0')
SPEAKER_00
tensor([[0.2051]], device='cuda:0')
SPEAKER_00
tensor([[0.1541]], device='cuda:0')
SPEAKER_02
tensor([[0.1770]], device='cuda:0')
SPEAKER_01
tensor([[0.1751]], device='cuda:0')
SPEAKER_02
tensor([[0.17

In [11]:
import os
for method in allMethods:
    try:
        os.mkdir("new_diar/" + method)
    except FileExistsError:
        print(f"Папка '{method}' уже существует.")

In [21]:
allMethods = ["deepFilterNet1","deepFilterNet1_normalized","deepFilterNet2","deepFilterNet2_normalized",
             "deepFilterNet3","deepFilterNet3_normalized"]

In [93]:
from pydub import AudioSegment

def speakers_detection(audio_path, rttm_path, output_path):
    audio = AudioSegment.from_file(audio_path)
    
    with open(rttm_path, 'r') as file:
        lines = file.readlines()
    
    samples_res = []
    for sample in samples:
        signal1, fs1 = torchaudio.load("interviewer_samples/" + sample)
        max_speaker = ""
        max_score = 0;
        for speaker in get_all_speakers(rttm_path):
            score_count = 0
            time = 0
            prediction_sum = 0
            prediction_count = 0
            for i, line in enumerate(lines):
                parts = line.strip().split()
                if parts[7] == speaker:
                    start_time = float(parts[3]) * 1000  # convert to milliseconds
                    duration = float(parts[4]) * 1000  # convert to milliseconds
                    end_time = start_time + duration
                    
                    if duration > 1000:
                        cropped_audio = audio[start_time:end_time]
                        path = f"{output_path}/cropped_{i}.wav"
                        cropped_audio.export(path, format="wav")
                        signal2, fs2 = torchaudio.load(path)
                        #print(end_time)
                        #embeddings = classifier.encode_batch(signal2)
                        score, prediction = verification.verify_batch(signal1, signal2)
                        if prediction:
                            prediction_sum += 1
                        prediction_count += 1
                        score_count += score
                        #print(score_count)
                        time += duration
            #print(prediction_count)
            #print(prediction_sum)
            avg_score = score_count/(time/1000)
            #print(time)
            #print(avg_score)
            if avg_score > max_score:
                max_score = avg_score
                max_speaker = speaker
        samples_res.append([sample, max_speaker, max_score])
        
    max_score = 0
    max_speaker = ""
    max_sample = ""
    for res in samples_res:
        if res[2] > max_score:
            max_score = res[2]
            max_speaker = res[1]
            max_sample = res[0]
    print(max_score)
    print(max_speaker)
    print(max_sample)

In [94]:
speaker_detection("audio/default/2.wav", "diarization/default/2.rttm", "crop")

38
0
100256.0
tensor([[0.0463]], device='cuda:0')
45
45
228690.0
tensor([[0.1290]], device='cuda:0')
1
1
5280.0
tensor([[0.0629]], device='cuda:0')
16
5
52836.0
tensor([[0.0696]], device='cuda:0')
38
3
100256.0
tensor([[0.0525]], device='cuda:0')
45
45
228690.0
tensor([[0.0989]], device='cuda:0')
1
1
5280.0
tensor([[0.0687]], device='cuda:0')
16
5
52836.0
tensor([[0.0747]], device='cuda:0')
38
15
100256.0
tensor([[0.0845]], device='cuda:0')
45
45
228690.0
tensor([[0.1054]], device='cuda:0')
1
1
5280.0
tensor([[0.0585]], device='cuda:0')
16
7
52836.0
tensor([[0.0715]], device='cuda:0')
38
12
100256.0
tensor([[0.0773]], device='cuda:0')
45
0
228690.0
tensor([[0.0198]], device='cuda:0')
1
0
5280.0
tensor([[0.0022]], device='cuda:0')
16
0
52836.0
tensor([[0.0250]], device='cuda:0')
tensor([[0.1290]], device='cuda:0')
SPEAKER_03
interviewer_female1.wav


In [4]:
def get_all_speakers(rttm_path):
    with open(rttm_path, 'r') as file:
        lines = file.readlines()
    speakers = set()
    for i, line in enumerate(lines):
        parts = line.strip().split()
        speakers.add(parts[7])
    return speakers

In [11]:
for elem in get_all_speakers(mainPath + diarDirStr + ref + "1.rttm"):
    print(elem)

Other_person
Interviewer
Other_person2
Person


In [6]:
mainPath = "C:/Users/sasha/OneDrive/Desktop/НИР/New Research/new_audio/"
default = "default"
norm = "normalized"

defPath =  default + "/"
normPath = norm + "/"

directory_files_default = os.listdir(mainPath + defPath)
directory_files_normalized = os.listdir(mainPath + normPath)

In [7]:
directory_files_default

['92.wav',
 '93.wav',
 '94.wav',
 '95.wav',
 '96.wav',
 '97.wav',
 '98.wav',
 '99.wav']

In [ ]:
allMethods = ["default","normalized","MTL","MTL_Normalized","MetricGAN","MetricGAN_Normalized",
              "MetricGAN_MTL","MetricGAN_MTL_Normalized","MTL_MetricGAN","MTL_MetricGAN_Normalized",
              "deepFilterNet1","deepFilterNet1_normalized","deepFilterNet2","deepFilterNet2_normalized",
             "deepFilterNet3","deepFilterNet3_normalized"]